DROP TABLE "REFERRED_TO" CASCADE CONSTRAINTS;
DROP TABLE "ASSESSMENT_RULES" CASCADE CONSTRAINTS;
DROP TABLE "REFERRAL_REASON" CASCADE CONSTRAINTS;
DROP TABLE "CHECKS_IN" CASCADE CONSTRAINTS;
DROP TABLE "DEPT_PROVIDES_SERVICE" CASCADE CONSTRAINTS;
DROP TABLE "MEDICAL_FACILITY" CASCADE CONSTRAINTS;
DROP TABLE "CERTIFICATIONS" CASCADE CONSTRAINTS;
DROP TABLE "FACILITY_CERTIFIED" CASCADE CONSTRAINTS;
DROP TABLE "STAFF" CASCADE CONSTRAINTS;
DROP TABLE "MEDICAL_STAFF" CASCADE CONSTRAINTS;
DROP TABLE "NON_MEDICAL_STAFF" CASCADE CONSTRAINTS;
DROP TABLE "SERVICE_DEPARTMENT" CASCADE CONSTRAINTS;
DROP TABLE "FACILITY_HAS_DEPT" CASCADE CONSTRAINTS;
DROP TABLE "SECONDARY_WORKS_DEPT" CASCADE CONSTRAINTS;
DROP TABLE "DEPT_PROVIDES_SERVICE" CASCADE CONSTRAINTS;
DROP TABLE "BODY_PARTS" CASCADE CONSTRAINTS;
DROP TABLE "SPECIALIZED_FOR" CASCADE CONSTRAINTS;
DROP TABLE "SERVICES" CASCADE CONSTRAINTS;
DROP TABLE "PERFORMED_USING" CASCADE CONSTRAINTS;
DROP TABLE "PATIENT" CASCADE CONSTRAINTS;
DROP TABLE "SEVERITY" CASCADE CONSTRAINTS;
DROP TABLE "SYMPTOMS" CASCADE CONSTRAINTS;
DROP TABLE "REASONS" CASCADE CONSTRAINTS;
DROP TABLE "EQUIPMENTS" CASCADE CONSTRAINTS;
DROP TABLE "AFFECTED_INFO" CASCADE CONSTRAINTS;
DROP TABLE "RULE_PROIRITY" CASCADE CONSTRAINTS;


SELECT cols.table_name, cols.column_name, cols.position, cons.status, cons.owner
FROM all_constraints cons, all_cons_columns cols
WHERE cols.table_name = 'REFERRAL_REASON'
AND cons.constraint_type = 'P'
AND cons.constraint_name = cols.constraint_name
AND cons.owner = cols.owner
ORDER BY cols.table_name, cols.position;





