CREATE TABLE COFFEES1 (COF_NAME VARCHAR(32), SUP_ID INTEGER,  PRICE FLOAT, SALES INTEGER, TOTAL INTEGER);

INSERT INTO COFFEES1 VALUES ('Colombian', 101, 7.99, 0, 0);

INSERT INTO COFFEES1 VALUES ('French_Roast', 49, 8.99, 0, 0);	

INSERT INTO COFFEES1 VALUES ('Colombian_Decaf', 101, 8.99, 0, 0);
